version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: imabhijeetkarne/todo-backend:latest
    container_name: todo-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - todo-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: imabhijeetkarne/todo-frontend:latest
    container_name: todo-frontend
    ports:
      - "5000:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - todo-network
    restart: unless-stopped

networks:
  todo-network:
    driver: bridge